project:
  type: website
  output-dir: docs

website:
  title: "Mecham Musings"
  site-url: https://www.matthewmec.github.io
  description: "A Simple Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: solar
    css: styles.css



